#!/usr/bin/env node
/* tools/auto-expose.js — #2 Stage 2 safety net.
 *
 * THE PROBLEM THIS SOLVES
 * Each .mjs is bundled by esbuild as an isolated IIFE (build.js), so a module's
 * top-level declarations are module-private at runtime. Before the ESM
 * migration these files were flat classic scripts whose top-level decls were
 * implicit globals, read by other modules and by app-main.js as bare globals or
 * via window.X. Those reads break the moment a module is isolated — and the
 * breakage is INVISIBLE to tsc (it only sees TS-typed bare refs) and to the
 * Node suite (it's a browser-boot ReferenceError), so it only surfaced as a
 * 14-minute Playwright red. This tool removes the guesswork.
 *
 * WHAT IT DOES
 * Parses every .mjs (acorn), computes each module's top-level declarations, and
 * regenerates a single marked exposure block per module that re-publishes those
 * names on globalThis — EXCEPT names that collide across modules (declared in
 * more than one bundle file), which are per-module private helpers (api, _norm,
 * on/emit, …) that MUST stay isolated; the genuinely-shared ones among them are
 * already exposed explicitly by their own module. app-main.js is included in the
 * collision scan because it shares the page's global scope as a classic script.
 *
 * Exposure uses `const __expg = /** @type {any} *\/ (globalThis)` so it is
 * tsc-valid for names without ambient .d.ts decls.
 *
 * USAGE
 *   node tools/auto-expose.js          # rewrite the exposure block in each .mjs
 *   node tools/auto-expose.js --check  # exit 1 if any block is stale/missing
 *
 * The --check mode runs in tests/run.sh so a forgotten exposure fails the gate
 * locally and deterministically, not as a cryptic CI Playwright failure. When
 * the import-rewiring phase lands real imports, this whole mechanism is deleted.
 */
"use strict";
var fs = require("fs");
var path = require("path");
var acorn = require("acorn");

var ROOT = path.resolve(__dirname, "..");
var CHECK = process.argv.indexOf("--check") !== -1;

var MARK = "/* #2 Stage 2 interim (auto-expose.js): re-publish this module's";
// Classic scripts that share the page global scope alongside the bundle. They
// are NOT bundled but their top-level names participate in collision detection.
var CLASSIC_PEERS = ["app-main.js"];

function topLevelNames(file, sourceType) {
  var src = fs.readFileSync(path.join(ROOT, file), "utf8");
  var ast;
  try {
    ast = acorn.parse(src, { ecmaVersion: "latest", sourceType: sourceType });
  } catch (e) {
    console.error("[auto-expose] parse failed: " + file + " — " + e.message);
    process.exit(2);
  }
  var names = [];
  ast.body.forEach(function (n) {
    if (n.type === "FunctionDeclaration" && n.id) names.push(n.id.name);
    else if (n.type === "ClassDeclaration" && n.id) names.push(n.id.name);
    else if (n.type === "VariableDeclaration")
      n.declarations.forEach(function (d) {
        if (d.id.type === "Identifier") names.push(d.id.name);
      });
  });
  return names;
}

var mjs = fs.readdirSync(ROOT).filter(function (f) { return /\.mjs$/.test(f); }).sort();

// Build owner map across all bundle files + classic peers to find collisions.
var owners = Object.create(null);
function record(name, file) { (owners[name] = owners[name] || new Set()).add(file); }
mjs.forEach(function (f) { topLevelNames(f, "module").forEach(function (n) { record(n, f); }); });
CLASSIC_PEERS.forEach(function (f) {
  if (fs.existsSync(path.join(ROOT, f))) topLevelNames(f, "script").forEach(function (n) { record(n, f); });
});
var collides = function (n) { return n === "global" || owners[n].size > 1; };

// Strip any prior exposure block — both this tool's marker and the earlier
// hand-rolled "#2 Stage 2 interim: expose …" blocks. The block body is only
// `__expg.x = x;` lines (no braces), so the first lone `}` line closes it.
var STRIP = /\n*\/\* #2 Stage 2 interim[\s\S]*?\n\}\n?/g;

function desiredBlock(names) {
  if (!names.length) return "";
  var body = names.map(function (n) { return "  __expg." + n + " = " + n + ";"; }).join("\n");
  return "\n" + MARK + " non-colliding top-level\n" +
    "   declarations as globals. esbuild isolates each .mjs to an IIFE, so other\n" +
    "   modules' and app-main.js's bare-global / window.X reads would otherwise\n" +
    "   break. Generated by `npm run expose`; verified by `npm run expose:check`\n" +
    "   in the gate. Removed when the import-rewiring phase lands real imports. */\n" +
    "{\n  const __expg = /** @type {any} */ (globalThis);\n" + body + "\n}\n";
}

var stale = [];
mjs.forEach(function (f) {
  var p = path.join(ROOT, f);
  var src = fs.readFileSync(p, "utf8");
  // Strip any prior block, normalize to a single trailing newline, then append
  // the fresh block at EOF (after any export statement — exports are hoisted, so
  // placement is irrelevant, and appending keeps this idempotent).
  var base = src.replace(STRIP, "\n").replace(/\s*$/, "\n");
  var names = topLevelNames(f, "module").filter(function (n) { return !collides(n); });
  names = Array.from(new Set(names)).sort();
  var block = desiredBlock(names);
  var next = block ? base + block : base;
  if (next !== src) {
    stale.push(f);
    if (!CHECK) fs.writeFileSync(p, next);
  }
});

if (CHECK) {
  if (stale.length) {
    console.error("[auto-expose] STALE exposure in " + stale.length + " module(s):\n  " + stale.join("\n  "));
    console.error("Run `npm run expose` and commit the result.");
    process.exit(1);
  }
  console.log("[auto-expose] OK — all " + mjs.length + " modules' exposure blocks are current.");
} else {
  console.log("[auto-expose] rewrote " + stale.length + " module(s); " + mjs.length + " scanned.");
}
